spring.application.name=backendProject

spring.profiles.active=dev

jwt.accessTokenExpirationTime=1000000
jwt.refreshTokenExpirationTime=86400000
jwt.secretKey=ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ
#secretKey는 아무문자열로 조합하고 512바이트만 넘으면됨