spring.application.name=backendProject

spring.profiles.active=dev

jwt.accessTokenExpirationTime=1000000
jwt.refreshTokenExpirationTime=86400000
jwt.secretKey=ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ
#secretKey는 아무문자열로 조합하고 512바이트만 넘으면됨



#google
spring.security.oauth2.client.registration.google.client-id=1095403877871-rd0f4akamsud40kbu447v2p5o8g9ctg1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code


#kakao
spring.security.oauth2.client.registration.kakao.client-id= bf0c3d3e06a640d762061a08913f58bc
spring.security.oauth2.client.registration.kakao.client-secret=9nLShnCNWv4DTTEEghcqB9R7BFd98cE4
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id