spring.application.name=backendProject

spring.profiles.active=dev

jwt.accessTokenExpirationTime=1000000
jwt.refreshTokenExpirationTime=86400000
jwt.secretKey=ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ
#secretKey\uB294 \uC544\uBB34\uBB38\uC790\uC5F4\uB85C \uC870\uD569\uD558\uACE0 512\uBC14\uC774\uD2B8\uB9CC \uB118\uC73C\uBA74\uB428



#google -> \uC7AC\uBC1C\uAE09\uBC1B\uC74C
spring.security.oauth2.client.registration.google.client-id=1095403877871-rd0f4akamsud40kbu447v2p5o8g9ctg1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code


#kakao -> \uC7AC\uBC1C\uAE09\uBC1B\uC74C \uD655\uC778\uC694\uB9DD
spring.security.oauth2.client.registration.kakao.client-id= bf0c3d3e06a640d762061a08913f58bc
spring.security.oauth2.client.registration.kakao.client-secret=9nLShnCNWv4DTTEEghcqB9R7BFd98cE4
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

#actuator and metric and prometheus
#prometheus \uC804\uC6A9 \uC564\uB4DC\uD3EC\uC778\uD2B8 \uC0DD\uC131
management.prometheus.metrics.export.enabled=true
#prometheus \uC5D4\uB4DC\uD3EC\uC778\uD2B8\uB97C \uB178\uCD9C
management.endpoints.web.exposure.include=*
#\uC564\uB4DC \uD3EC\uC778\uD2B8\uC5D0\uC11C \uC5B4\uB5A4 \uC815\uBCF4\uB97C \uBCF4\uC5EC\uC904\uC9C0 \uC124\uC815
management.endpoint.health.show-details=always
#never -> \uC808\uB300 \uC0C1\uC138 \uC815\uBCF4 \uC81C\uACF5 \uC548\uD568 (\uD56D\uC0C1 status\uB9CC \uC751\uB2F5)
#when-authorized -> \uC778\uC99D\uB41C \uC0AC\uC6A9\uC790/\uB85C\uCEEC \uC694\uCCAD\uC5D0\uB9CC \uC0C1\uC138 \uC815\uBCF4 \uC81C\uACF5 (\uAE30\uBCF8\uAC12, \uAD8C\uC7A5)
#always -> \uD56D\uC0C1 \uC0C1\uC138 \uC815\uBCF4 \uD3EC\uD568 (\uC678\uBD80/\uB0B4\uBD80 \uAD00\uACC4\uC5C6\uC774 \uC0C1\uC138 \uC815\uBCF4 \uB178\uCD9C, \uAC1C\uBC1C\u00B7\uD14C\uC2A4\uD2B8\uC6A9)

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight([%-3level]) %cyan(%logger{5}) - %msg%n

spring.elasticsearch.uris=http://localhost:9200

#searchlog
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=search-log-group
spring.kafka.consumer.auto-offset-reset=earliest

#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

management.health.elasticsearch.enabled=false